2022-04-30 06:15:05,137 [INFO] - setting paTH TO download
2022-04-30 06:15:05,137 [INFO] - SETTING PROFILE SETTINGS FOR FIREFOX
2022-04-30 06:15:05,137 [INFO] - Adding firefox profile
2022-04-30 06:15:05,137 [INFO] - 

2022-04-30 06:15:05,137 [INFO] - ====== WebDriver manager ======
2022-04-30 06:16:00,483 [INFO] - Current firefox version is 99.0
2022-04-30 06:16:00,483 [INFO] - Get LATEST geckodriver version for 99.0 firefox
2022-04-30 06:16:00,811 [INFO] - Getting latest mozilla release info for v0.31.0
2022-04-30 06:16:00,983 [INFO] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.31.0/geckodriver-v0.31.0-win64.zip
2022-04-30 06:16:01,483 [INFO] - Driver has been saved in cache [C:\Users\TEMP\.wdm\drivers\geckodriver\win64\v0.31.0]
2022-04-30 06:16:04,594 [ERROR] - Message: Service C:\Users\TEMP\.wdm\drivers\geckodriver\win64\v0.31.0\geckodriver.exe unexpectedly exited. Status code was: 3221226505
Traceback (most recent call last):
  File "S:\IT Dev\Testing_Environment\enverus_automation\enverus_script_test.py", line 278, in <module>
    driver=webdriver.Firefox(executable_path=GeckoDriverManager().install(),firefox_profile=profile)
  File "C:\Python3.8.5\production_environment\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "C:\Python3.8.5\production_environment\lib\site-packages\selenium\webdriver\common\service.py", line 98, in start
    self.assert_process_still_running()
  File "C:\Python3.8.5\production_environment\lib\site-packages\selenium\webdriver\common\service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service C:\Users\TEMP\.wdm\drivers\geckodriver\win64\v0.31.0\geckodriver.exe unexpectedly exited. Status code was: 3221226505

